name: 'build-and-publish'
description: 'Perform metanorma site generate and upload pages artifact'
inputs:
  token:
    description: Required if destination='auto'. Just pass secrets.GITHUB_TOKEN
    default: ''
  source-path:
    description: Source path, usually directory where configuration
      (manifest) file is
    default: '.'
  output-dir:
    description: Output directory for generated site
    default: _site
  config-file:
    description: 'Metanorma configuration (mainfest) file'
    default: metanorma.yml
  agree-to-terms:
    description: 'Agree / Disagree with all third-party licensing terms
      presented (WARNING: do know what you are agreeing with!)'
    default: '' # false
  use-bundler:
    description: 'Run in bundler'
    default: '' # false
  destination:
    description: 'What is a target of the action. At this moment `default`, `gh-pages` or `artifact` is available'
    default: default
outputs:
  gh-pages-enabled:
    description: "Random number"
    value: ${{ steps.pages-status.outputs.enabled }}

runs:
  using: "composite"
  steps:
    - uses: actions-mn/cache@v1

    - uses: actions-mn/site-gen@v1
      with:
        source-path: ${{ inputs.source-path }}
        config-file: ${{ inputs.config-file }}
        output-dir: ${{ inputs.output-dir }}
        agree-to-terms: ${{ inputs.source-path }}
        use-bundler: ${{ inputs.use-bundler }}

    - if: ${{ inputs.destination == 'default' }}
      id: pages-status
      env:
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        if [ "$GH_TOKEN" = "" ]; then
          echo "Error! For destination=default you have to pass token input also."
          exit 1
        fi

        if ! type gh > /dev/null; then
          curl -L https://github.com/cli/cli/releases/download/v2.24.3/gh_2.24.3_linux_amd64.tar.gz | tar xz --strip-components=2 -C /usr/local/bin/ gh_2.24.3_linux_amd64/bin/gh
        fi

        if gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "repos/${GITHUB_REPOSITORY}/pages"; then
          echo "enabled=true" >> $GITHUB_OUTPUT
        else
          echo "enabled=false" >> $GITHUB_OUTPUT
        fi

    - if: ${{ inputs.destination == 'gh-pages' || steps.pages-status.outputs.enabled == 'true' }}
      uses: actions/configure-pages@v2

    - if: ${{ inputs.destination == 'gh-pages' || steps.pages-status.outputs.enabled == 'true' }}
      uses: actions/upload-pages-artifact@v1
      with:
        path: ${{ inputs.source-path }}/${{ inputs.output-dir }}

    - if: ${{ inputs.destination == 'artifact' || steps.pages-status.outputs.enabled == 'false' }}
      uses: actions/upload-artifact@v3
      with:
        name: metanorma-build-artifact
        path: ${{ inputs.source-path }}/${{ inputs.output-dir }}
