name: test

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          sudo apt-get install yamllint
          yamllint action.yml

  test-docker:
    runs-on: ubuntu-latest
    container:
      image: metanorma/metanorma
    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v3
      with:
        repository: metanorma/mn-samples-cc
        path: cc

    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source-path: cc
        agree-to-terms: true

    - uses: andstor/file-existence-action@v1
      with:
        files: cc/_site/index.html

  test-default-public:
    name: Test default on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v3
      with:
        repository: metanorma/mn-samples-cc
        path: cc

    - uses: actions-mn/setup@main

    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source-path: cc
        agree-to-terms: true

    - uses: andstor/file-existence-action@v1
      with:
        files: cc/_site/index.html

  test-artifact-public:
    name: Test artifact on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v3
      with:
        repository: metanorma/mn-samples-cc
        path: cc

    - uses: actions-mn/setup@main

    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source-path: cc
        agree-to-terms: true
        destination: artifact

    - uses: andstor/file-existence-action@v1
      with:
        files: cc/_site/index.html
